-- ================================================
-- 电商商品种子数据 (由电商商品资料.xlsx生成)
-- 共100件商品，3个分类
-- 热销: 19件 (每分类TOP3 + 全局TOP10补充)
-- 生成时间: 2026-07-10
-- ================================================

-- 使用方法: 在Supabase SQL Editor中执行此文件
-- 或通过 psql 命令行导入

-- 清空现有商品数据(可选)
-- DELETE FROM products;
-- ALTER SEQUENCE products_id_seq RESTART WITH 1;

INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('iPhone 15 Pro Max 256GB', 'iPhone 15 Pro Max 256GB 旗舰登场！搭载业界首款3nm工艺A17 Pro芯片，性能狂飙再升级，游戏、创作、多任务处理行云流水。钛金属机身轻盈坚固，搭配超视网膜XDR显示屏，色彩更鲜活，细节更锐利。Pro级摄像头系统，捕捉震撼光影瞬间，长焦端拍摄能力再突破。iOS 17系统加持，隐私安全与流畅体验双重保障，256GB大存储轻松容纳精彩生活。科技与美学的完美融合，开启你的旗舰新体验！', 9999.0, 11999, 'https://s.coze.cn/image/_gbVFw9Q_Sk/', '数码', 999, 26301, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('AirPods Pro 第二代', 'AirPods Pro 第二代，苹果真无线降噪耳机，搭载全新H2芯片，带来更强降噪性能与通透模式。主动降噪深度升级，隔绝外界纷扰；自适应通透模式智能调节环境音，对话更自然。空间音频技术打造沉浸式听感，搭配动态头部追踪，声场如临现场。续航持久，单次充电可使用6小时，搭配充电盒总续航达30小时。支持MagSafe无线充电，使用更便捷。IPX4防水防汗，运动无忧。全新设计贴合耳型，佩戴稳固舒适，重新定义无线降噪体验。', 1899.0, 2279, 'https://s.coze.cn/image/U68zf-9xCMs/', '数码', 999, 18819, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('MacBook Air M3 13寸', '【MacBook Air M3 13寸】苹果轻薄本标杆之作！M3芯片澎湃性能，18小时超长续航告别电量焦虑，视网膜显示屏色彩细腻真实，无风扇静音设计时刻冷静高效。超窄边框+全尺寸键盘，便携与体验双重升级，无论是创意设计、办公处理还是影音娱乐，都能轻松应对，重新定义移动办公的极致轻薄与性能平衡。', 9499.0, 11399, 'https://s.coze.cn/image/0z68mLp4dZs/', '数码', 999, 33009, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('真无线蓝牙耳机 黑色', '【真无线蓝牙耳机 黑色】蓝牙5.3极速连接，低延迟游戏影音更沉浸！IPX5级防水，运动出汗/雨天通勤无惧泼溅。28小时超长续航，单次满电使用8小时，搭配充电仓告别电量焦虑。半入耳式人体工学设计，佩戴稳固舒适，久戴不痛。高清通话降噪，通话清晰无杂音。轻巧便携，一手掌握，黑色经典百搭，随时随地开启无线自由！', 299.0, 359, 'https://s.coze.cn/image/CnM45qBdT5A/', '数码', 999, 16106, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('头戴式降噪耳机', '【40mm大动圈+35dB主动降噪】沉浸式音乐体验来袭！强劲40mm大动圈单元，低频澎湃、高频清亮，细节纤毫毕现。35dB深度降噪黑科技，一键隔绝通勤喧嚣/办公室干扰，图书馆/地铁秒变专属音乐舱。柔软蛋白皮耳罩+记忆棉填充，久戴无压；轻量化机身+可折叠设计，出行便携无忧。蓝牙5.3低延迟，追剧游戏音画同步，开启你的「无界降噪」音乐之旅！', 599.0, 719, 'https://s.coze.cn/image/TIdu22OtCKw/', '数码', 999, 32873, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Apple Watch Series 9', 'Apple Watch Series 9，科技与时尚的完美融合！搭载超视网膜XDR显示屏，亮度提升至1000尼特，户外强光下也清晰可见。新增双核心S9 SiP芯片，性能强劲，操作响应更快。内置高精度传感器，全天候监测心率、血氧、睡眠质量，健康数据一目了然。支持独立通话、离线Siri、海量第三方应用，运动模式丰富，跑步、游泳、骑行等场景轻松适配。搭配磁吸无线充电，30分钟快充80%电量，续航持久无忧。无论是商务通勤还是运动健身，都是您的智能生活好搭档！', 3299.0, 3959, 'https://s.coze.cn/image/dvM-IIiY8jg/', '数码', 999, 28668, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('华为 Watch GT 4', '华为Watch GT 4智能手表，搭载强劲芯片与智能功耗管理技术，实现长达14天持久续航，告别频繁充电焦虑。支持精准健康监测，含心率、血氧、睡眠质量分析及压力管理，守护全天候健康状态。高清AMOLED大屏，支持触控操作，适配多种运动模式，跑步、游泳等运动数据实时追踪，助你科学运动。IP68级防水，日常使用无忧。鸿蒙生态深度互联，手机消息、通话一键管理，让科技与生活无缝衔接。', 1488.0, 1786, 'https://s.coze.cn/image/KmR-_weG6bQ/', '数码', 999, 47785, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('智能手环', '【高清AMOLED彩屏】告别黑白小屏！1.3英寸高清触控屏，色彩细腻显示清晰，阳光下依旧清晰可见。【健康双监测】实时心率监测+血氧饱和度检测，全天候守护健康数据，运动、通勤、睡眠状态一手掌握。【超长续航】一次充电使用14天，IP68级防水，游泳、洗澡无需摘卸，运动生活全适配！【智能交互】抬手亮屏、消息推送、久坐提醒、女性健康管理，生活小助手，时刻在线！', 299.0, 359, 'https://s.coze.cn/image/RBXeG-IGApI/', '数码', 999, 42000, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('小米14 Pro', '小米14 Pro搭载旗舰级骁龙8 Gen3处理器，性能强劲流畅，多任务处理游刃有余。徕卡专业光学镜头，还原真实光影，无论是风景大片还是人像特写，都能拍出徕卡经典质感，记录生活每一刻精彩。精致工艺与前沿科技融合，带来卓越使用体验，开启高端旗舰新标杆。', 5299.0, 6359, 'https://s.coze.cn/image/KzOTqOIhXsM/', '数码', 999, 45494, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('OPPO Find X7 Ultra', 'OPPO Find X7 Ultra搭载双潜望长焦影像系统，哈苏专业调校加持，双焦段覆盖远摄场景，无论远景细节还是近景质感都能精准捕捉。超光影人像模式，哈苏自然色彩还原，让每一帧都如电影大片般震撼。性能与影像双重旗舰配置，为您打造专业级拍摄体验，记录生活中每一处精彩瞬间。', 6499.0, 7799, 'https://s.coze.cn/image/O2RtfEmuupo/', '数码', 999, 49862, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('vivo X100 Pro', 'vivo X100 Pro搭载蔡司一英寸主摄，超大底传感器带来更纯净的感光能力与更细腻的成像细节。无论是白天强光下的高动态范围拍摄，还是夜晚暗光环境中的低噪点表现，都能轻松驾驭。搭配蔡司专业镜头调校，色彩还原自然真实，人像虚化过渡丝滑，每一张照片都如同专业大片。从日常记录到旅行创作，都能捕捉到令人惊艳的精彩瞬间，让你的摄影体验再升级！', 4999.0, 5999, 'https://s.coze.cn/image/B27lDTTbGNI/', '数码', 999, 26137, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('荣耀 Magic 6 Pro', '荣耀Magic 6 Pro震撼登场！搭载旗舰级骁龙8 Gen3处理器，性能狂飙无上限，多任务切换丝滑流畅，游戏影音体验拉满。更配备卫星通信黑科技，深山远洋也能一键呼救，安全无界！高清大屏+强劲续航，科技与实用完美融合，开启你的智慧新体验！', 5499.0, 6599, 'https://s.coze.cn/image/jGXuzpjIjWE/', '数码', 999, 21318, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Sony WH-1000XM5', 'Sony WH-1000XM5旗舰降噪耳机，搭载新一代V1处理器，自适应降噪技术精准隔绝环境噪音，通勤/办公/旅行都能沉浸私域空间。30小时超长续航，快充10分钟播放5小时。高解析度音频支持LDAC高清传输，40mm镀铝液晶高分子振膜还原细腻音质。触控操作+多点连接，折叠设计便携省心，30mm镀铝液晶高分子振膜+DSEE Extreme数字声音增强引擎，让每段旋律都如临现场。', 2999.0, 3599, 'https://s.coze.cn/image/XjoqxYeBZEs/', '数码', 999, 26013, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Bose QC45', 'Bose QC45 经典降噪耳机，搭载全新声学科技，主动降噪深度升级，轻松隔绝外界喧嚣。柔软蛋白皮耳罩+记忆海绵，佩戴零压感，全天舒适无负担。40小时超长续航，Type-C快充10分钟即享5小时畅听。高解析度音频技术，还原细腻音质，无论是通勤、办公还是旅行，都能沉浸于专属音乐世界。经典设计搭配精致细节，彰显品质格调，是追求降噪体验与音质享受的不二之选。', 2299.0, 2759, 'https://s.coze.cn/image/yynwXs3tGmQ/', '数码', 999, 34404, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Redmi K70 Pro', 'Redmi K70 Pro震撼登场！搭载旗舰级骁龙8 Gen3处理器，性能狂飙无压力，多任务、高负载游戏统统流畅驾驭！2K分辨率高清大屏，细腻画质每一帧都惊艳，无论是追剧还是操作都带来沉浸式视觉享受。强悍性能与高清屏幕的完美结合，满足你对旗舰体验的所有期待，现在入手，开启你的极速科技生活！', 3599.0, 4319, 'https://s.coze.cn/image/tiv65XBJNTo/', '数码', 999, 39942, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('一加 Ace 3', '一加Ace 3搭载旗舰级骁龙8 Gen2处理器，性能强劲，流畅运行各类应用与大型游戏；配备5500mAh超大容量电池，搭配智慧省电技术，续航持久无忧，重度使用也能轻松应对。无论是畅快游戏还是日常使用，都能带来出色体验，是追求高性能与长续航用户的理想之选。', 2999.0, 3599, 'https://s.coze.cn/image/sCbN2ru8aGs/', '数码', 999, 9950, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('联想小新 Pro 16', '联想小新Pro 16，搭载全新酷睿Ultra处理器，性能强劲，多任务处理游刃有余。16英寸2.5K高清大屏，细腻画质与舒适视觉体验，无论是办公创作还是影音娱乐都表现出色。轻薄机身设计，便携出行无负担，为你带来高效、流畅的使用感受，开启移动办公新体验！', 5999.0, 7199, 'https://s.coze.cn/image/vUplVFy4JKM/', '数码', 999, 5742, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('华硕灵耀14', '华硕灵耀14，14英寸2.8K OLED超感屏，100% P3广色域+10.7亿色显示，色彩鲜活细腻如临其境。仅1.2kg轻薄机身，搭配CNC一体成型工艺，商务便携无负担。搭载英特尔酷睿处理器，性能强劲且能效出众，多任务处理流畅高效。细节之处尽显品质，窄边框设计与长续航能力，让每一次使用都成为享受，是轻办公与创意设计的理想之选。', 6999.0, 8399, 'https://s.coze.cn/image/xQE0_2Y4ckE/', '数码', 999, 10180, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('ThinkBook 14+', 'ThinkBook 14+商务笔记本，性能强劲，办公效率倍增！14英寸高清大屏，窄边框设计，视野更开阔。丰富接口一应俱全，满足多设备连接需求，Type-C、USB、HDMI等接口，轻松应对会议、出差等场景。轻薄机身搭配长续航，随时随地高效工作，是商务人士的得力助手，也是学生党学习的好伙伴。', 5499.0, 6599, 'https://s.coze.cn/image/Er1M-rc5W-o/', '数码', 999, 21616, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('华为 MatePad Pro', '华为MatePad Pro搭载13.2英寸OLED原色全面屏，色彩精准还原，视觉沉浸感拉满。搭配强劲性能与长效续航，无论是办公创作还是影音娱乐，都能流畅应对。轻薄机身兼顾便携与质感，多屏协同功能让办公效率倍增，是您移动办公与娱乐的理想伙伴。', 5499.0, 6599, 'https://s.coze.cn/image/tzJrs9f9_Xs/', '数码', 999, 43597, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('iPad Air 6', 'iPad Air 6 搭载 M2 芯片，性能强劲，轻松应对多任务处理与创意工作。支持 Apple Pencil，书写绘画如纸上般流畅自然。轻薄机身搭配绚丽 Liquid 视网膜显示屏，无论是学习、办公还是娱乐，都能带来出色体验，开启你的移动创作新方式。', 4799.0, 5759, 'https://s.coze.cn/image/Nd1nNKP-eZ4/', '数码', 999, 10631, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('iPhone 15 Pro 256GB', 'iPhone 15 Pro 256GB震撼登场！搭载业界首款3nm工艺A17 Pro芯片，性能狂飙再升级，游戏、创作皆如虎添翼。钛金属边框，比不锈钢轻约14%，质感与轻薄完美平衡，握持更舒适。超视网膜XDR显示屏，亮度再突破，细节纤毫毕现。iOS生态无缝联动，让每一次操作都流畅丝滑。256GB大容量，轻松容纳海量内容，开启你的专业级移动体验新境界！', 8999.0, 10799, 'https://s.coze.cn/image/k4vpK2PBzaw/', '数码', 999, 36319, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('MacBook Pro 14寸', 'MacBook Pro 14寸搭载M3 Pro芯片，专业级性能引擎澎湃输出！无论是视频剪辑、3D建模还是多任务处理，均能流畅应对。14.2英寸Liquid视网膜XDR显示屏，P3广色域+原彩显示，色彩精准还原；1080P FaceTime高清摄像头+六扬声器音响系统，视频会议/影音体验全面升级。长达22小时超长续航，轻巧机身内藏强悍散热，专业生产力与便携性完美融合，为创意工作者量身打造的移动工作站！', 14999.0, 17999, 'https://s.coze.cn/image/JzB_UGyuuy0/', '数码', 999, 48965, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Galaxy S24 Ultra', 'Galaxy S24 Ultra搭载旗舰级骁龙8 Gen3处理器，性能强劲，流畅运行多任务与大型应用。内置S Pen手写笔，支持精准书写、笔记记录与创意绘画，办公创作更高效。搭配超视觉影像系统，捕捉精彩瞬间，开启移动影像新体验。', 9999.0, 11999, 'https://s.coze.cn/image/ZFiF1fRKZ2Q/', '数码', 999, 35482, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('降噪耳机 真无线', '【真无线降噪耳机】蓝牙5.3极速连接，低延迟游戏/影音无卡顿！主动降噪深度隔绝环境音，通勤、办公、旅行沉浸静享音乐盛宴。半入耳式人体工学设计，久戴不痛，续航单次8小时+充电仓32小时超长续航。高清通话ENC降噪，通话清晰如面对面。IPX4级防水，运动出汗无忧。轻巧便携，一触即连，开启你的专属静谧音世界！', 399.0, 479, 'https://s.coze.cn/image/nDrHmCWO7Ns/', '数码', 999, 5914, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('优衣库 UT联名T恤', '【优衣库UT联名T恤】100%优质纯棉面料，亲肤透气，柔软舒适，久穿不闷热。潮流联名印花设计，个性吸睛，轻松点亮日常穿搭。简约百搭版型，适配各种下装与风格，无论是休闲出街、校园通勤还是居家放松，都能展现独特品味。经典基础款与潮流元素结合，轻松打造属于你的时尚态度，是衣橱里不可或缺的百搭单品。', 99.0, 119, 'https://s.coze.cn/image/kF7clVzLCmM/', '服饰', 999, 22497, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('优衣库 U系列T恤', '优衣库U系列T恤，甄选高品质亲肤棉质面料，触感柔软细腻如云朵轻拥肌肤，透气排汗让肌肤时刻清爽自在。经典简约圆领设计，利落大方不挑脸型，轻松适配各种穿搭风格。无论是单穿打造随性休闲风，还是内搭叠穿都游刃有余，日常通勤、校园生活、周末出游皆能完美hold住，是衣橱里不可或缺的百搭基础款，助你轻松解锁舒适与时尚的双重体验。', 79.0, 95, 'https://s.coze.cn/image/rxB24cmlx40/', '服饰', 999, 276868, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('优衣库 AIRismT恤', '优衣库AIRismT恤，采用黑科技速干面料，时刻保持肌肤干爽！吸湿排汗性能卓越，闷热天气也能清爽自在。轻盈透气的质地，宛如第二层肌肤般舒适，日常通勤、运动健身都适配。简约百搭的设计，轻松融入各种穿搭场景，让舒适与时尚并存，是夏季衣橱必备的清爽单品！', 99.0, 119, 'https://s.coze.cn/image/pmg_2PV0-tI/', '服饰', 999, 70128, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('阿迪达斯三叶草卫衣', '【阿迪达斯三叶草经典卫衣】精选优质纯棉抓绒面料，触感柔软亲肤，保暖性与透气性兼备。胸前经典三叶草Logo醒目点缀，简约设计中彰显品牌辨识度。宽松版型适配多种身形，日常出街、校园通勤或休闲聚会都能轻松驾驭，是衣橱里永不过时的百搭单品，为你打造舒适又有型的穿搭体验。', 499.0, 599, 'https://s.coze.cn/image/L7x__26wDw8/', '服饰', 999, 225078, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('阿迪达斯运动卫衣', '阿迪达斯运动卫衣，采用先进保暖科技，锁住温度不流失，寒冬运动也能暖意十足。弹力面料设计，活动自如无束缚，跑步、健身、日常穿搭都舒适自在。简约时尚的版型，百搭易穿，无论是搭配运动裤还是牛仔裤，都能展现潮流运动风，让你在运动与休闲间无缝切换，轻松打造型格穿搭。', 549.0, 659, 'https://s.coze.cn/image/etlBJ_pj5Ho/', '服饰', 999, 68736, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('耐克 Air Max 270', '耐克Air Max 270，革命性270度大气垫设计，覆盖足弓至后跟区域，带来卓越缓震体验。轻盈鞋面搭配透气网布，贴合脚型更舒适。中底稳定支撑，外底耐磨橡胶提升抓地力，无论是日常出行还是运动健身，都能为双脚提供全天候舒适防护，每一步都如云端漫步般轻松自在！', 999.0, 1199, 'https://s.coze.cn/image/Y9n9TYhx8-Y/', '服饰', 999, 82923, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('耐克 Dunk Low', '耐克Dunk Low复古板鞋，以经典皮革鞋面重塑街头潮流！细腻皮革打造质感鞋面，透气耐磨双在线，搭配标志性Swoosh勾饰，复古中透着利落。中底缓震科技加持，行走舒适不疲惫，无论是搭配工装裤还是牛仔裙，都能轻松拿捏复古运动风。从校园到街头，从日常出街到潮流打卡，这双Dunk Low都是彰显个性的绝佳单品，让你在复古浪潮中脱颖而出！', 899.0, 1079, 'https://s.coze.cn/image/LdUfk_PwLy4/', '服饰', 999, 118166, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('耐克 Air Force 1', '【耐克Air Force 1经典小白鞋】百年经典重塑潮流基因！标志性空军一号轮廓，搭配轻盈缓震中底，行走间释放隐形能量。头层牛皮打造细腻质感，3M反光细节点亮街头态度，无论是工装裤、百褶裙还是oversize卫衣，都能完美融合。从校园通勤到街头出片，一双搞定全场景穿搭，真正的百搭王者！每一处走线都复刻传奇工艺，让经典永不过时。', 799.0, 959, 'https://s.coze.cn/image/rVg21torBTk/', '服饰', 999, 281154, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('ZARA 粉色连衣裙', 'ZARA粉色连衣裙，温柔气质拉满！轻盈飘逸的裙摆随风摇曳，行走间自带灵动韵律；精心收腰设计巧妙勾勒腰线，一秒穿出好身材比例。柔和马卡龙粉调，衬得肌肤白皙透亮，无论是约会、通勤还是闺蜜小聚，都能让你成为焦点，轻松拿捏法式浪漫与现代简约的平衡。', 399.0, 479, 'https://s.coze.cn/image/aNOiHDTy_Gc/', '服饰', 999, 216033, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('ZARA 碎花连衣裙', '【ZARA碎花连衣裙】法式优雅新定义！V领设计勾勒天鹅颈，泡泡袖温柔修饰手臂线条，复古碎花图案自带浪漫滤镜，轻盈面料透气亲肤。中长款剪裁适配多种身形，无论是约会、通勤还是下午茶，都能让你瞬间成为焦点，轻松拿捏法式慵懒氛围感~', 459.0, 551, 'https://s.coze.cn/image/M0QBLwoAQAM/', '服饰', 999, 92330, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('ZARA 波点连衣裙', '【ZARA波点连衣裙】复古优雅风席卷而来！经典波点元素碰撞法式浪漫，细腻面料垂坠感满分，温柔包裹身形。A字裙摆巧妙修饰胯部与大腿线条，行走间灵动飘逸，适配多种场合——通勤搭配西装外套干练大气，约会单穿尽显温柔气质，度假风外搭开衫慵懒随性。长度恰到好处，小个子显高、高个子更添优雅，轻松穿出复古摩登感，这个夏天必备的氛围感战袍，让你在人群中脱颖而出！', 429.0, 515, 'https://s.coze.cn/image/5t684F2_Wpo/', '服饰', 999, 133347, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('ZARA 白色连衣裙', '🌞ZARA白色雪纺连衣裙，一秒拿捏度假氛围感！轻盈垂坠的雪纺面料，透气不闷热，自带温柔光泽感。简约圆领+收腰A字版型，藏肉显瘦超友好，无论是漫步沙滩还是都市约会都能轻松驾驭。纯净白色百搭不挑人，搭配草帽与凉鞋，瞬间化身慵懒法式美人，让你在人群中脱颖而出，开启一场浪漫的夏日出逃计划~', 379.0, 455, 'https://s.coze.cn/image/pzswDlj_pSg/', '服饰', 999, 134050, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('CK 男士内裤 3条装', '【CK男士纯棉内裤3条装】精选100%优质精梳棉，触感柔软亲肤如云朵般包裹肌肤，透气吸湿告别闷热黏腻。经典弹力腰头设计，3cm加宽弹性带不卷边不勒腰，8小时久坐仍舒适如初。人体工学剪裁贴合身形，无侧缝拼接减少摩擦感，3条不同色系满足日常轮换需求。简约CK Logo低调彰显品质，从居家放松到运动出行，全方位守护私密空间的干爽与自在，每一寸面料都传递着轻奢生活态度。', 299.0, 359, 'https://s.coze.cn/image/048IZeXexCA/', '服饰', 999, 187791, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Levi''s 501 牛仔裤', 'Levi''s 501经典直筒牛仔裤，百年传承的赤耳丹宁工艺！精选重磅原浆丹宁布，未经过预缩水处理，初穿即展现自然垂坠感，越穿越合身。标志性红色小旗标、皮牌与后袋刺绣，复刻1873年经典设计。直筒版型适配各种身材，中腰设计优化腰线，耐磨耐穿却不失柔软，日常通勤、街头出片皆出彩，是衣橱里永不过时的牛仔灵魂单品！', 799.0, 959, 'https://s.coze.cn/image/0rMSeU13PGo/', '服饰', 999, 155913, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Levi''s 破洞牛仔裤', 'Levi''s破洞牛仔裤，经典修身版型勾勒利落身形，弹力牛仔面料带来无拘无束的舒适体验。精心设计的破洞细节，在复古与潮流间找到完美平衡，无论是日常出街还是约会聚会，都能轻松打造个性造型。耐磨抗皱，持久保持挺括质感，让你在时尚与实用间自在切换，成为衣橱里不可或缺的百搭单品。', 699.0, 839, 'https://s.coze.cn/image/V0o7grvOyW0/', '服饰', 999, 52027, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Levi''s 直筒牛仔裤', 'Levi''s经典直筒牛仔裤，采用深邃蓝水洗工艺，呈现自然做旧质感与复古韵味。舒适立体剪裁，贴合身形却无束缚感，中腰设计修饰腰线，裤型利落百搭。甄选高品质牛仔布，耐磨耐穿不易变形，日常通勤、休闲出街皆能轻松驾驭，是衣橱中永不过时的百搭单品。', 749.0, 899, 'https://s.coze.cn/image/t5yrJBWBqek/', '服饰', 999, 99572, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('H&M 基础卫衣', 'H&M基础卫衣，甄选高品质纯棉面料，柔软亲肤透气不闷热，日常穿搭舒适无负担。经典简约圆领设计，利落大方不挑人，轻松适配各种内搭外穿场景。宽松版型包容身形，无论是单穿还是叠搭都随性自在，基础款永不过时，是衣橱里的百搭王炸单品，让你轻松打造休闲时尚感。', 199.0, 239, 'https://s.coze.cn/image/_G2pUbPsG8w/', '服饰', 999, 233358, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('H&M 针织毛衣', 'H&M高领针织毛衣，宽松慵懒版型适配多种身形，软糯亲肤面料带来云朵般触感。高领设计锁住温暖，秋冬单穿或叠搭外套都超有氛围感。简约大气的风格轻松驾驭通勤、约会等场合，让你在保暖的同时，轻松成为街头焦点。', 249.0, 299, 'https://s.coze.cn/image/r3CFEaxeSG4/', '服饰', 999, 282819, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('GAP Logo卫衣', 'GAP经典Logo卫衣，连帽设计舒适自在，胸前精致刺绣Logo彰显品牌辨识度。精选优质面料，柔软亲肤透气，版型宽松显瘦，适配多种身形。无论是日常休闲出街，还是居家放松，都能轻松驾驭，简约中透出随性态度，是衣橱里永不过时的百搭单品。', 299.0, 359, 'https://s.coze.cn/image/cT4t-av5Nss/', '服饰', 999, 104534, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('GAP 圆领T恤', 'GAP经典圆领T恤，甄选优质纯棉面料，柔软亲肤透气不闷热，贴身穿舒适感满分。简约圆领设计，百搭不挑人，轻松适配各种穿搭场景。多色可选，基础黑、纯净白、温柔粉等经典色系，满足日常通勤、休闲出游等多元需求，一件轻松打造随性自在的风格，是衣橱里不可或缺的百搭单品。', 149.0, 179, 'https://s.coze.cn/image/YscfxQmRdGI/', '服饰', 999, 156915, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('优衣库 羽绒服', '【优衣库轻薄羽绒服】精选优质鸭绒填充，轻盈蓬松却保暖力MAX！便携易收纳，出差旅行塞进行李箱毫无压力～简约版型适配各种内搭，通勤、休闲、校园场景都能轻松hold住。防风面料锁住温度，-5℃也能安心出门～日常穿搭不臃肿，时尚保暖二合一，秋冬衣橱必备单品！', 599.0, 719, 'https://s.coze.cn/image/MRSJWt1_I_w/', '服饰', 999, 59818, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('优衣库 阔腿裤', '优衣库高腰阔腿裤，解锁显瘦新姿势！经典高腰设计，自然收腹提臀，视觉拉长腿部线条，秒变大长腿既视感。精选弹力面料，轻盈透气不紧绷，久坐也自在，通勤逛街都舒适。宽松垂坠感剪裁，藏肉效果MAX，搭配T恤、衬衫都超有范儿，轻松驾驭多种风格，日常出街必备神裤！', 199.0, 239, 'https://s.coze.cn/image/UGmSBloFEIM/', '服饰', 999, 23941, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('Nike 运动夹克', 'Nike运动夹克，精选防风面料，有效抵御寒风侵袭，为你打造温暖舒适的户外环境。经典立领设计，不仅提升整体造型的利落感，更能在降温时护住颈部，保暖又有型。无论是日常通勤还是户外慢跑，都能凭借出色的防风性能和简约大气的外观，成为你的时尚运动首选。轻盈剪裁，活动自如，让你在运动中也能保持风度与温度的平衡。', 599.0, 719, 'https://s.coze.cn/image/Fp4CbbT41NE/', '服饰', 999, 97778, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('阿迪达斯运动裤', '阿迪达斯运动裤采用高弹透气面料，贴合身形又不失活动自由，无论是跑步健身还是日常休闲都能舒适应对。经典简约设计搭配品牌标志性细节，轻松适配多种穿搭风格。腰部弹性抽绳设计，自由调节松紧度，运动时稳固不滑落，日常穿着更自在。耐磨抗皱面料，久穿不易变形，让你在运动与生活场景中都能保持利落有型。', 299.0, 359, 'https://s.coze.cn/image/ng-odSUVsPA/', '服饰', 999, 45313, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('优衣库 休闲长裤', '【优衣库休闲长裤】精选100%纯棉面料，柔软透气不闷热，直筒修身剪裁适配各种身形，日常通勤、休闲出街都能轻松驾驭。简约百搭的设计，搭配T恤、衬衫都出彩，无论是单穿还是叠穿都很有质感，让你舒适自在又不失时尚感，轻松打造随性高级的日常穿搭！', 179.0, 215, 'https://s.coze.cn/image/_KQT9Ve3_U4/', '服饰', 999, 147435, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('三只松鼠坚果礼盒', '三只松鼠坚果礼盒，精选10种优质坚果，每一颗都饱满香脆！包含巴旦木、核桃、腰果等多种美味，科学配比营养更均衡。独立小包装设计，干净卫生，随时随地享受美味。无论是节日送礼、走亲访友，还是居家分享，都是贴心之选，让你轻松传递心意与美味！', 128.0, 154, 'https://s.coze.cn/image/qXMWf6kAIQU/', '美食', 999, 351035, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('良品铺子肉脯礼盒', '【良品铺子肉脯礼盒】精选三种经典风味：原味咸香醇厚、黑胡椒微辣过瘾、藤椒麻辣鲜香！严选优质猪肉后腿肉，经黄金配比腌制，慢火烘烤锁住肉汁，每一片都肉质紧实Q弹，咸甜适中不腻口。独立小包装设计，干净卫生，追剧、办公、茶歇随时解馋！无论是自食还是送礼都超有面，快把这份‘肉香盛宴’带回家吧~', 98.0, 118, 'https://s.coze.cn/image/3zRakLnq86U/', '美食', 999, 430323, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('百草味每日坚果', '【百草味每日坚果30包装】精选7种优质坚果果干，科学配比营养更均衡！每天一小包，轻松补充蛋白质、膳食纤维和不饱和脂肪酸~独立小包装干净卫生，上班/追剧/健身随时开袋即食，锁住新鲜好滋味。无论是早餐搭配还是办公室零食，都是健康轻食的贴心选择，给忙碌生活注入满满活力！', 79.0, 95, 'https://s.coze.cn/image/VY3aalU1i6U/', '美食', 999, 458439, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('来伊份蜜饯果干', '来伊份蜜饯果干精选多种天然鲜果，酸甜交织的美妙滋味在舌尖绽放！每一颗果干都保留着果肉的饱满与营养，无多余添加更安心。无论是办公室解馋、午后小憩，还是追剧时光，都是您的绝佳伴侣。独立小包装设计，方便携带，随时随地享受这份自然馈赠的甜蜜与清爽。', 68.0, 82, 'https://s.coze.cn/image/O8A5MqRJyn4/', '美食', 999, 355000, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('卫龙辣条大礼包', '【卫龙辣条大礼包20包】经典川香麻辣暴击味蕾！精选小麦粉+优质辣椒，传统工艺发酵更入味，Q弹劲道越嚼越香。独立小包装干净便携，追剧/办公/聚会随时解馋，一口回到童年辣条魂！囤货必备的解馋神器，辣度适中不呛喉，好吃到停不下来！', 39.0, 47, 'https://s.coze.cn/image/IYns_GW0Tok/', '美食', 999, 344184, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('稻香村月饼礼盒', '【稻香村经典广式月饼礼盒】8枚精致装，传承百年工艺，一口解锁广式甜香精髓！精选小麦粉酥皮，包裹绵密内馅，莲蓉蛋黄咸甜交织，五仁果仁醇厚饱满，每一口都是老味道的安心与满足。中秋团圆送礼/自食佳品，传统铁罐包装尽显大气，佳节氛围拉满，把这份“稻”香心意带回家！', 168.0, 202, 'https://s.coze.cn/image/6d2y8ebFF5A/', '美食', 999, 56593, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('广州酒家蛋黄酥', '【广州酒家蛋黄酥】精选海鸭咸蛋黄，搭配绵密豆沙内馅，酥皮层次分明如云朵般轻盈。一口咬下，酥皮簌簌飘落，咸香蛋黄与清甜豆馅在舌尖交融，甜而不腻，咸香适口。传统工艺手工开酥，层层起酥入口即化，每一口都是广式点心的经典风味，早餐配茶、午后解馋、馈赠亲友的绝佳选择，让味蕾邂逅岭南风情的醇厚滋味。', 58.0, 70, 'https://s.coze.cn/image/nJanvfK4beM/', '美食', 999, 310900, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('五芳斋粽子礼盒', '【五芳斋粽子礼盒】嘉兴非遗工艺匠心打造！10只经典组合（内含鲜肉粽、蛋黄肉粽、豆沙粽等），精选糯米Q弹饱满，咸甜交织风味十足。真空锁鲜包装，开袋即食方便快捷，传统箬叶包裹清香四溢，每一口都是地道嘉兴味！端午送礼/家庭分享绝佳选择，传承百年好滋味，让团圆时刻更添仪式感！', 138.0, 166, 'https://s.coze.cn/image/oGPugPR_t5k/', '美食', 999, 422638, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('三全速冻水饺', '三全速冻水饺（猪肉白菜馅），传承经典家常风味！精选新鲜猪肉与脆嫩白菜黄金配比，皮薄如纸却韧性十足，一口咬开满满都是饱满馅料，鲜香肉汁瞬间迸发。0添加防腐剂，锁鲜工艺锁住食材本味，无需解冻直接下锅，煮制3-5分钟即可享用。早餐快手餐、夜宵暖心食，速冻锁鲜更省心，让美味无需等待，轻松满足全家味蕾需求！', 32.0, 38, 'https://s.coze.cn/image/tXaFCfohLbc/', '美食', 999, 483977, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('思念手打鱼丸', '【思念手打鱼丸】严选深海野生鲜鱼，拒绝冷冻边角料！老师傅手工捶打8小时，保留鱼肉90%以上活性蛋白，颗颗Q弹似弹珠，咬开瞬间鲜汁迸发！0淀粉添加，低脂高蛋白，老人小孩都能放心吃。煮汤、火锅、烧烤随心搭配，热辣鲜香一口沦陷，让每一餐都充满海洋的鲜甜暴击！', 28.0, 34, 'https://s.coze.cn/image/__bpACuL_dE/', '美食', 999, 204025, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('康师傅红烧牛肉面', '康师傅红烧牛肉面5连包，经典红烧风味传承多年！浓郁醇厚的红烧汤底，精选劲道面条，搭配Q弹卤蛋与鲜香配料，一口唤醒味蕾记忆。开水冲泡3分钟即享热乎美味，无论是匆忙早餐、加班简餐还是解馋时刻，都是你的暖心选择。独立包装干净卫生，囤货必备，让美味随时相伴！', 25.0, 30, 'https://s.coze.cn/image/JJtKFQr8H7I/', '美食', 999, 174794, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('统一老坛酸菜面', '统一老坛酸菜面，传承经典老坛发酵工艺！精选优质酸菜，酸爽开胃，辣得过瘾，一口唤醒味蕾！劲道面条Q弹爽滑，搭配浓郁汤底，每一口都是地道川味享受。5连包超值组合，早餐、夜宵、加班党必备，随时随地来一碗，满足你的胃！', 25.0, 30, 'https://s.coze.cn/image/6Lj6RqpFzh0/', '美食', 999, 394033, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('螺霸王螺蛳粉', '【螺霸王螺蛳粉3袋装】正宗柳州风味！精选广西螺蛳慢火熬制金汤，醇厚鲜香；Q弹爽滑米粉搭配酸笋、花生、腐竹等7种配料，酸香浓郁，辣而不燥。开袋即煮，10分钟享地道嗦粉快乐，囤3袋更划算！让你足不出户，随时随地解馋过瘾！', 45.0, 54, 'https://s.coze.cn/image/ea8eMLl27Cw/', '美食', 999, 406342, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('李子柒螺蛳粉', '🔥李子柒螺蛳粉｜网红爆款再升级！地道柳州风味，料包多到溢出来！劲道米粉裹满浓郁螺蛳汤底，搭配Q弹腐竹、酸笋、花生、木耳、酸豆角等6大配料，一口嗦出酸辣鲜香！古法熬制汤底，鲜而不腥，辣而不燥，还原街头巷尾的地道嗦粉快乐！独立包装干净卫生，冷水下锅10分钟即享，懒人速食也能吃出仪式感，追剧解馋必备神器！', 52.0, 62, 'https://s.coze.cn/image/2ByS05hhRGE/', '美食', 999, 357569, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('海底捞自热火锅', '🔥海底捞自热火锅，地道牛油麻辣锅底，一口点燃味蕾！精选优质食材，搭配Q弹蔬菜、嫩滑豆制品，分量超足吃到爽。15分钟自热即食，无需开火，随时随地享受火锅自由。独立小包装干净卫生，聚会、加班、追剧必备，让你足不出户也能get海底捞同款美味！', 39.0, 47, 'https://s.coze.cn/image/97-c4TqgxuI/', '美食', 999, 140185, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('自嗨锅自热火锅', '【自嗨锅麻辣牛肉自热火锅】随时随地开涮！精选大块麻辣牛肉，搭配Q弹宽粉、爽脆蔬菜，秘制麻辣汤底鲜香过瘾。无需开火，冷水加热15分钟即享热气腾腾的火锅盛宴，独立小包装干净便携，加班、追剧、户外出游必备！一人食也能轻松get的火锅自由，让美味随时随地“嗨”起来～', 35.0, 42, 'https://s.coze.cn/image/B5_GNEHHCEQ/', '美食', 999, 86372, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('旺旺雪饼 700g', '【旺旺雪饼700g】童年记忆里的香脆滋味！精选优质大米，传统工艺烘烤非油炸，入口酥松化渣，米香浓郁不甜腻。独立小包装设计，干净卫生易携带，无论是宅家追剧、办公室解馋，还是出游分享都超合适。经典白绿包装唤醒满满回忆杀，每一口都是童年的味道，囤上一箱，快乐加倍！', 35.0, 42, 'https://s.coze.cn/image/e9_EhDrvUK4/', '美食', 999, 206982, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('旺旺仙贝 700g', '【旺旺仙贝700g】经典童年味道升级回归！精选优质大米与小麦粉，经传统工艺烘焙，每一口都是咸香酥脆的极致体验。独立小包装设计，干净卫生易携带，无论是宅家追剧、朋友聚会，还是办公室解馋，都是绝佳搭档。严选原料配比，咸度适中不齁，米香浓郁层层迸发，酥脆口感让人欲罢不能。700g大容量分享装，全家共享更满足，囤货必备的经典零食，唤醒味蕾记忆的美味选择！', 32.0, 38, 'https://s.coze.cn/image/2fY9NOmseXo/', '美食', 999, 359990, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('奥利奥夹心饼干', '奥利奥经典巧克力夹心饼干，一口咬下酥香四溢！外层饼干采用优质小麦粉烘焙，口感松脆不粘牙；内部夹着浓郁丝滑的巧克力奶油，甜而不腻，层次丰富。传承百年工艺，经典配方带来熟悉的幸福味道，无论是早餐搭配牛奶，还是午后休闲解馋，都是绝佳选择。独立小包装设计，方便携带分享，随时随地享受美味时光~', 25.0, 30, 'https://s.coze.cn/image/u64wROmk4ZQ/', '美食', 999, 261678, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('好吃点坚果饼干', '好吃点坚果饼干，精选饱满核桃与香脆杏仁，黄金配比融入酥松饼身！每一口都能咬到真实坚果颗粒，口感层次丰富，酥而不腻。传统工艺烘焙，保留坚果原香与营养，早餐搭配牛奶、下午茶解馋小食，健康美味双在线！独立小包装设计，随时随地享受酥脆好滋味，追剧、办公都超合适~', 22.0, 26, 'https://s.coze.cn/image/r4Xq9hwfd0Y/', '美食', 999, 147849, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('达利园法式小面包', '达利园法式小面包，一口咬下松软如云，麦香与清甜在舌尖交融。独立小包装设计，干净卫生，随时随地都能享受这份甜蜜。早餐搭配牛奶开启元气一天，午后小憩来一块补充能量，追剧解馋也超合适，是你生活中不可或缺的美味小确幸。', 28.0, 34, 'https://s.coze.cn/image/vnqU2k6WiDQ/', '美食', 999, 71984, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('盼盼法式软面包', '盼盼法式软面包，每一口都是云朵般的绵软细腻！精选优质小麦粉，搭配天然乳源，发酵工艺锁住浓郁奶香。撕开面包体，蓬松组织细腻如丝，入口即化不粘牙，甜而不腻的醇厚麦香在舌尖绽放。独立小包装设计，便携又卫生，早餐、下午茶、加班解馋都合适，让你随时随地享受法式烘焙的浪漫美味，开启元气满满的一天！', 19.0, 23, 'https://s.coze.cn/image/KRGa1xCD7LU/', '美食', 999, 243519, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('百威啤酒 12罐', '【百威啤酒12罐】经典清爽口感，精选优质麦芽与啤酒花，入口麦香醇厚，泡沫细腻持久。冰镇后饮用，瞬间唤醒味蕾，是朋友聚会、家庭小酌的绝佳伴侣。12罐规格满足多人分享需求，随时随地畅饮无忧，为欢乐时刻注入冰爽活力！', 88.0, 106, 'https://s.coze.cn/image/0nMKTucgsUg/', '美食', 999, 73905, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('青岛啤酒 12罐', '【青岛啤酒12罐】百年匠心酿造，国民信赖的经典滋味！精选优质原料与传统工艺，酒体清亮澄澈，泡沫细腻持久，入口甘醇爽口，麦香与酒香完美融合。无论是朋友小聚、家庭分享，还是独酌放松，开一罐冰镇的青岛啤酒，瞬间唤醒味蕾，畅饮每一刻的惬意！12罐超值装，随时随地享受纯粹啤酒乐趣，品质之选，不容错过！', 68.0, 82, 'https://s.coze.cn/image/R_wbyemO9RY/', '美食', 999, 438687, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('雪花啤酒 12罐', '雪花啤酒12罐装，清爽淡爽口感，年轻潮流之选！精选优质原料，入口顺滑，泡沫细腻持久，带来冰爽畅饮体验。无论是朋友聚会、夏日消暑，还是独自小酌，都能轻松适配，开启愉悦时光。每一口都是纯粹麦香与清爽回甘的完美融合，是你日常休闲、社交场合的绝佳拍档。', 58.0, 70, 'https://s.coze.cn/image/bcCFld1ejnw/', '美食', 999, 93758, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('农夫山泉矿泉水', '农夫山泉天然矿泉水，源自大自然馈赠，每一滴都蕴含天然矿物质精华。水质清冽甘甜，口感纯净柔和，满足日常补水需求。24瓶整箱装，方便储存与携带，无论是居家饮用、办公解渴还是户外出行，都是您的安心之选。坚持天然水源地直采，品质稳定可靠，为健康生活保驾护航。', 48.0, 58, 'https://s.coze.cn/image/iWIeZJwSQVc/', '美食', 999, 109114, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('怡宝纯净水', '怡宝纯净水，源自严格品控的生产工艺，口感纯净无味，每一口都带来清爽体验。24瓶整箱装，满足家庭日常、办公饮用等多种场景需求，随时随地畅饮安心好水。优质水源+科学净化技术，品质值得信赖，是您健康饮水的贴心选择。', 45.0, 54, 'https://s.coze.cn/image/kdt7P8TCyjw/', '美食', 999, 209434, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('可口可乐 24罐', '【可口可乐24罐整箱】经典碳酸饮料，每一口都迸发鲜活气泡！源自百年配方，甜而不腻的焦糖香气与清爽口感完美融合，冰饮后瞬间唤醒味蕾，驱散夏日燥热与疲惫。无论是家庭聚会、朋友畅饮还是独自放松，24罐足量规格满足你对快乐气泡的所有想象，随时随地畅饮无忧，开启活力满满的快乐时光！', 59.0, 71, 'https://s.coze.cn/image/KSFTe9wwUpE/', '美食', 999, 490974, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('百事可乐 24罐', '【百事可乐24罐】经典清爽气泡水，每一口都迸发鲜活活力！甜度恰到好处，不齁不腻，搭配美食解腻又过瘾。冰镇后饮用，气泡在舌尖炸开，瞬间唤醒味蕾，带来畅爽体验。24罐大容量装，家庭分享、聚会畅饮都合适，随时随地享受这份快乐！', 55.0, 66, 'https://s.coze.cn/image/thrDhas4v7s/', '美食', 999, 360935, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('元气森林气泡水', '【元气森林白桃味气泡水】0糖0脂的清爽新选择！精选阳光白桃原香，搭配细腻气泡在舌尖迸发，每一口都是轻盈畅快的味觉盛宴。0负担配方，让你尽情享受甜润果香，无论是宅家追剧、办公提神，还是运动后解渴，都是你的元气搭档～一口唤醒活力，开启轻负担的健康生活！', 79.0, 95, 'https://s.coze.cn/image/lGKFydar0Lk/', '美食', 999, 155493, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('东鹏特饮 24罐', '东鹏特饮24罐整箱装，精选优质原料，科学配比牛磺酸、维生素B群等成分，快速补充能量。无论是加班熬夜、运动健身后，还是午后犯困时刻，一罐即可唤醒活力，提神醒脑，有效缓解疲劳感。口感清爽不腻，包装便携，随时随地为你注入满满动力，是都市生活、户外出行的能量好搭档！', 88.0, 106, 'https://s.coze.cn/image/tOmM3ybG8Nk/', '美食', 999, 103563, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('红牛功能饮料', '红牛功能饮料，精选优质原料科学配比，含牛磺酸、维生素B族等能量成分，快速补充体力、恢复活力。口感醇厚劲爽，每罐都是活力加油站！无论是运动健身后、加班熬夜时，还是驾车长途中，随时随地来一罐，瞬间唤醒状态，为你注入满满能量，轻松应对忙碌生活与挑战！', 108.0, 130, 'https://s.coze.cn/image/W9gkieRBVDI/', '美食', 999, 313394, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('特仑苏纯牛奶', '【特仑苏纯牛奶】源自黄金奶源带，每一滴都凝聚天然牧场的纯净能量。精选优质奶牛，科学饲养铸就卓越品质，蛋白质含量高达3.6g/100ml，远超国家标准，醇厚营养轻松吸收。从牧场到餐桌全程锁鲜，口感丝滑浓郁，自然奶香萦绕舌尖。无论是早餐搭配、午后补给，还是睡前滋养，都是您高品质生活的安心之选，让健康与美味时刻相伴！', 68.0, 82, 'https://s.coze.cn/image/TOrh-Y8kUWY/', '美食', 999, 114201, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('金典纯牛奶', '【金典纯牛奶】有机认证品质之选！精选优质奶源，每一滴都蕴含丰富营养。富含蛋白质、钙等多种关键营养素，营养全面易吸收，为您的健康加分。口感醇厚丝滑，自然奶香萦绕舌尖，无论是早餐搭配还是日常饮用，都是您和家人的安心之选。有机品质，值得信赖！', 65.0, 78, 'https://s.coze.cn/image/x9ArWKGsFRE/', '美食', 999, 480920, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('安慕希希腊酸奶', '【安慕希希腊酸奶】严选优质奶源，采用希腊传统发酵工艺，成就浓稠醇厚的丝滑质地！每一口都像云朵般绵密，0蔗糖添加更健康，富含优质蛋白质，为身体注入满满活力。早餐搭配面包、下午茶轻食、运动后补充能量，随时随地享受纯粹美味与营养守护，让健康生活从一杯好酸奶开始！', 58.0, 70, 'https://s.coze.cn/image/JIwQa0vzCfk/', '美食', 999, 433486, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('纯甄酸奶', '纯甄酸奶，以纯净配方为初心，严选优质奶源，每一口都是无添加的安心之味。细腻醇厚的口感，酸甜平衡恰到好处，给味蕾温柔拥抱。无多余添加，保留酸奶本真风味，无论是早餐搭配面包，还是午后休闲小食，都能带来纯粹的美味享受，让健康与美味轻松同行。', 52.0, 62, 'https://s.coze.cn/image/kN0aG8ujqWI/', '美食', 999, 420794, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('德芙丝滑巧克力', '德芙丝滑巧克力，甄选优质可可原料，以精湛工艺打造丝滑醇厚的味觉盛宴。入口瞬间，细腻质地如丝绸般融化，浓郁可可香气在舌尖缓缓释放，甜度恰到好处，余韵悠长。独立小包装设计，随时随地开启甜蜜时刻，无论是犒赏自己还是分享美好，都是绝佳选择。每一块都凝聚着德芙对品质的执着，带给你纯粹而愉悦的味蕾享受。', 45.0, 54, 'https://s.coze.cn/image/Q_Xxodn7cYk/', '美食', 999, 351345, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('费列罗金莎巧克力', '【费列罗金莎巧克力】经典榛仁夹心，每一口都藏着丝滑惊喜！外层裹着金箔质感的脆米巧克力，咬开瞬间榛仁的醇厚香气与丝滑内馅完美交融，甜而不腻的味觉盛宴。金箔包装精致奢华，无论是犒赏自己还是馈赠亲友，都尽显心意与品味。开启甜蜜时刻，让舌尖沉醉于这颗‘金莎’的浪漫魔力～', 118.0, 142, 'https://s.coze.cn/image/mX0y_NuSruw/', '美食', 999, 202434, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('好时KISSES巧克力', '【好时KISSES巧克力】经典水滴造型，每一颗都像被施了魔法的甜蜜小水滴！独立小包装设计，干净卫生，随时随地开启甜蜜时光。丝滑浓郁的巧克力口感，入口即化，醇厚可可香气在舌尖绽放，甜而不腻，幸福感瞬间拉满。无论是休闲解馋、办公提神，还是分享给朋友、装点派对，都是绝佳选择。快来把这份‘吻’住的甜蜜带回家吧！', 48.0, 58, 'https://s.coze.cn/image/ip6UWYwQeXw/', '美食', 999, 90290, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('徐福记沙琪玛', '徐福记沙琪玛，一口咬下松软如云，蛋香在舌尖层层绽放！精选优质小麦粉与鲜鸡蛋黄金配比，传统工艺慢火烘烤，入口即化却不失韧性。香甜不腻的口感，搭配酥软蓬松的质地，每一口都是纯粹的享受。无论是早餐搭配牛奶，还是午后休闲解馋，亦或是加班提神小食，都是绝佳选择。独立包装设计，干净卫生，随时随地满足你的味蕾渴望，开启甜蜜好时光！', 32.0, 38, 'https://s.coze.cn/image/jnd9k1AAQug/', '美食', 999, 78199, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('大白兔奶糖', '【大白兔奶糖】一口咬开童年回忆杀！精选优质奶源与麦芽糖浆黄金配比，入口先是丝滑奶香温柔漫开，接着是清甜不腻的糖体在舌尖化开，浓郁醇厚的味道瞬间唤醒味蕾记忆。独立小包装设计，随时随地都能分享这份甜蜜，无论是办公解馋、聚会分享还是童年情怀重温，都是绝佳选择。经典白瓷瓶包装+复古铁盒，既是美味零食，更是承载回忆的甜蜜信物，让奶香与快乐常伴左右~', 38.0, 46, 'https://s.coze.cn/image/dT2_D2R8GI8/', '美食', 999, 449743, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('旺仔牛奶 24罐', '旺仔牛奶24罐组合装，经典甜牛奶风味，醇厚香甜，大人小孩都爱喝！采用优质奶源，搭配科学配方，口感顺滑，营养美味。无论是早餐搭配面包，还是午后休闲小酌，亦或是作为家庭聚会的饮品，都是绝佳选择。24罐大容量包装，满足全家日常饮用需求，随时随地享受这份甜蜜与温暖。', 78.0, 94, 'https://s.coze.cn/image/Lqr_ujrPUr4/', '美食', 999, 339942, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('老干妈风味豆豉', '【老干妈风味豆豉】国民级下饭神器！精选贵州优质大豆发酵，搭配鲜辣豆豉与秘制香辛料，经传统工艺慢火熬制，酱香浓郁、咸香适口。颗粒分明的豆豉裹挟着醇厚油香，拌饭时拌入一勺，米饭瞬间迸发层次感；拌面条、蘸馒头、炒青菜……百搭吃法解锁无限美味，开瓶即食超方便，轻松拯救没胃口的餐桌！', 25.0, 30, 'https://s.coze.cn/image/erOMe8rOUYk/', '美食', 999, 176339, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('海天金标生抽', '海天金标生抽，精选优质原料，传统工艺与现代技术结合，鲜味醇厚自然，咸鲜适口。炒菜提鲜、凉拌增香、蘸食提味，一瓶搞定多种烹饪场景，是厨房调味的必备之选，让家常菜也能轻松出彩，为您的餐桌增添美味。', 35.0, 42, 'https://s.coze.cn/image/Rf4XbM_nCvM/', '美食', 999, 51622, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('李锦记蚝油', '李锦记蚝油，精选优质生蚝熬制，蚝香浓郁醇厚，每一滴都饱含海洋鲜韵。提鲜增味效果显著，无论是炒菜、炖煮还是蘸食，只需少许便能点亮菜品风味，让家常菜也能拥有餐厅级的鲜美体验。传统工艺与现代技术结合，品质稳定，是厨房提鲜的绝佳伴侣，为您的每一餐增添丰富口感与层次。', 38.0, 46, 'https://s.coze.cn/image/ZpCM1PvUKdI/', '美食', 999, 318129, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('双汇王中王火腿肠', '【双汇王中王火腿肠】经典国民美味，30年品质传承！精选优质猪肉为主料，肉质紧实弹牙，咸香适口不腻。黄金配比工艺锁住肉汁，每一口都饱满多汁。独立小包装设计，早餐煎烤、泡面搭档、户外零食随心享，国民信赖的安心之选，让美味随时随地相伴！', 18.0, 22, 'https://s.coze.cn/image/-DO9UIltjR0/', '美食', 999, 445045, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('金锣肉多多火腿肠', '金锣肉多多火腿肠，真材实料看得见！精选优质猪肉，含肉量超高，每一口都能吃到满满的肉香。Q弹爽滑的口感，肉质紧实有嚼劲，无论是早餐煎烤、泡面搭档，还是追剧解馋，都是绝佳选择。开袋即食，方便快捷，让美味随时相伴，是您餐桌上的贴心小食，更是忙碌生活的能量补给站！', 22.0, 26, 'https://s.coze.cn/image/CsHEtReZrUc/', '美食', 999, 406023, 4.5, false);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('乐事薯片原味', '乐事原味薯片，传承经典配方！精选优质马铃薯，黄金比例调味，每一片都薄脆酥香，入口即化。咸香适中不腻，一口唤醒味蕾，追剧、聚会、休闲时刻的绝佳搭档！独立包装干净卫生，分享更自在，让快乐随时在线！', 35.0, 42, 'https://s.coze.cn/image/8mxzQKhBj3s/', '美食', 999, 462814, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('可比克薯片番茄味', '可比克番茄味薯片，精选阳光番茄与优质马铃薯黄金配比！酸甜浓郁的番茄酱汁均匀裹满每一片薯片，入口瞬间迸发清新果香，轻咬即酥脆掉渣，咸甜交织的绝妙口感在舌尖层层绽放。独立小包装设计，无论是办公解馋、追剧分享还是朋友聚会，都能随时随地享受这份“咔嚓”脆响的快乐。0反式脂肪酸配方，美味无负担，让你轻松get童年回忆里的经典味道！', 28.0, 34, 'https://s.coze.cn/image/CRgDoAJJ8Mk/', '美食', 999, 489865, 4.5, true);
INSERT INTO products (name, description, price, original_price, image_url, category, stock, sales_count, rating, is_hot) VALUES ('三只松鼠夏威夷果', '三只松鼠夏威夷果，每一颗都经过精挑细选！个大饱满的果仁，轻轻一剥就能露出完整的果核，奶香四溢的独特风味，入口酥脆又带着天然的清甜。精选优质产地原料，保留坚果最本真的营养与口感，无论是追剧休闲还是办公解馋，都是绝佳选择。独立小包装设计，干净卫生，方便携带，随时随地享受这份来自大自然的馈赠！', 59.0, 71, 'https://s.coze.cn/image/nOPrNolrWTc/', '美食', 999, 376561, 4.5, false);